export const BREED_GROUPS = {
  Dairy: [
    "Holstein",
    "Jersey",
    "Guernsey",
    "Ayrshire",
    "Brown Swiss",
    "Milking Shorthorn",
    "Dutch Belted",
    "Red Dane",
  ],
  Beef: [
    "Angus",
    "Red Angus",
    "Hereford",
    "Charolais",
    "Simmental",
    "Limousin",
    "Brahman",
    "Brangus",
    "Santa Gertrudis",
    "Beefmaster",
    "Shorthorn",
    "Gelbvieh",
    "Chianina",
    "Belgian Blue",
    "Wagyu",
    "Highland",
    "Texas Longhorn",
    "Galloway",
    "Murray Grey",
    "South Devon",
    "Salers",
    "Piedmontese",
    "Maine-Anjou",
  ],
  "Dual-Purpose": ["Dexter", "Red Poll", "Devon", "Pinzgauer"],
  "Zebu / Tropical": ["Gir", "Sahiwal", "Nelore", "Boran", "Tharparkar"],
  "Indigenous / Regional": [
    "Red Sindhi",
    "Kankrej",
    "Ongole",
    "Hariana",
    "N'Dama",
    "Sokoto Gudali",
  ],
  Other: ["Crossbred", "Mixed", "Other"],
};
